name: cine_nest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Native calls
  app_settings: ^6.1.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.4

  # UI elements
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  skeleton_text: ^3.0.1
  cupertino_icons: ^1.0.8
  blurrycontainer: ^2.1.0
  cached_network_image: ^3.3.1

  # Backend
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  meilisearch: ^0.17.0

  # Auth
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # Flutter services
  provider: ^6.1.5
  go_router: ^15.1.2
  internet_connection_checker: ^3.0.1


dev_dependencies:
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0F1518"
  android: true
  ios: true
  web: true
  image: assets/images/splash.png
  android_12:
    image: assets/images/android_splash_logo.png
    color: "#0F1518"


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animation_files/

  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa-Trial-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nexa-Trial-Bold.ttf
          weight: 700