name: cine_nest
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  # Native calls
  app_settings: ^6.1.1
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_dotenv: ^5.2.1


  # UI elements
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  skeleton_text: ^3.0.1
  cupertino_icons: ^1.0.8
  blurrycontainer: ^2.1.0
  cached_network_image: ^3.3.1
  animated_text_kit: ^4.2.3
  card_swiper: ^3.0.1


  # Backend
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  firebase_core: ^3.13.1
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  meilisearch: ^0.17.0

  # Auth
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1

  # Flutter services
  provider: ^6.1.5
  go_router: ^15.1.2
  internet_connection_checker: ^3.0.1
  url_launcher: ^6.3.1
  intl: ^0.20.2


dev_dependencies:
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#673AB7"
  image: assets/images/splash_screen_app_icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animation_files/

  fonts:
    - family: PlusJakarta
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  # image_path: assets/images/app_icon.png"
  # For iOS
  image_path_ios: "assets/images/app_icon.png"
  remove_alpha_ios: true # Icons with alpha channel are not allowed in the Apple App Store.
  image_path_ios_dark_transparent: "assets/images/app_icon.png"
  desaturate_tinted_to_grayscale_ios: true
  background_color_ios: "#673AB7"
  # For Android
  image_path_android: "assets/images/app_icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#673AB7"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_foreground_inset: 20
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
    background_color: "#673AB7"
    theme_color: "#673AB7"