// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfZYXk7IM6xSFM41Dr3ALpuwrraxlpaxE',
    appId: '1:1086383075801:web:4b4cc41443525fd20729c8',
    messagingSenderId: '1086383075801',
    projectId: 'cine-nest-demo',
    authDomain: 'cine-nest-demo.firebaseapp.com',
    storageBucket: 'cine-nest-demo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5L36RJBt1wjP8bB2-iwTnyjWTxXncfE',
    appId: '1:1086383075801:android:a20fa4a6d7ef07a10729c8',
    messagingSenderId: '1086383075801',
    projectId: 'cine-nest-demo',
    storageBucket: 'cine-nest-demo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSAyG8jVv6jmUoB-9UCCpJlbtesMICT_o',
    appId: '1:1086383075801:ios:dfaeb2caebe461810729c8',
    messagingSenderId: '1086383075801',
    projectId: 'cine-nest-demo',
    storageBucket: 'cine-nest-demo.firebasestorage.app',
    iosBundleId: 'chervenkov.aleksandar.cineNest.cineNest',
  );
}
